Tile sheet with different sized tiles #1008
mapeditor/tiled pull request #3339
Opened 2022-04-21 23:48 UTC by devnewton

I have implemented the tile sheet with different sized tiles support with:

- only two (optional) addition to the xml/json format : top and left attributes for image tag ;
- a little GUI change: a new image rect property.

The goal is to use manually drawn spritesheets through tile collection without breaking Tiled normal workflow/code.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.8" tiledversion="1.8.4" name="plop" tilewidth="100" tileheight="200" tilecount="3" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
 <tile id="0">
  <image width="100" height="200" top="10" left="20" source="squirrel.png"/>
 </tile>
 <tile id="1">
  <image width="100" height="100" top="0" left="200" source="squirrel.png"/>
 </tile>
 <tile id="2">
  <image width="95" height="48" top="50" left="878" source="squirrel.png"/>
 </tile>
</tileset>
```

![image](https://user-images.githubusercontent.com/103828758/164567971-571cd4a5-9533-4fee-a16e-f8e419a541b0.png)

![image](https://user-images.githubusercontent.com/103828758/164567922-954e25c6-fac1-49d2-9f90-bc0f9f0420e0.png)

![image](https://user-images.githubusercontent.com/103828758/164568805-265680e6-2413-4bbe-a0e9-460695e40b96.png)

2022-05-04 15:37 UTC, bjorn requested changes
Thanks for getting this feature started! As it is, I think there are some problems that we'll need to address, see also my inline comments.

The main issue is as I mentioned at https://github.com/mapeditor/tiled/issues/1008#issuecomment-838154607, we're looking for a solution to this that also works for tileset images. If we just add `top` and `left` attributes to the `image` element, then there is no way to cover the other use-case. Besides that, re-using the `width` and `height` attributes is a compatibility issue and leads to unexpected behavior when images are resized.

I've just proposed an alternative storage at https://github.com/mapeditor/tiled/issues/2863#issuecomment-1117500495, and I think we could adjust this PR to use that format. I'd welcome your thoughts on this!

2022-05-08 10:13 UTC, devnewton commented on src/libtiled/maptovariantconverter.cpp
> +            }
I've removed the top/left stuff.

2022-05-08 10:13 UTC, devnewton commented on src/libtiled/imagereference.cpp
> +    return pixmap.copy(QRect(topLeft, size));
I reverted this pixmap copy.

2022-05-08 10:14 UTC, devnewton commented
I've made the suggested change to use x,y,width,height properties at tile level: https://github.com/mapeditor/tiled/pull/3339/commits/783284cce2d42cc4c7b3932f61b03c88a58dc39a

2022-05-11 10:31 UTC, bjorn commented on src/tiled/tileanimationeditor.cpp
> +        setTile(nullptr);        // It may be gone
@devnewton Can you shed some light on why you added this?

2022-05-11 10:48 UTC, bjorn approved these changes
Sometimes it's hard to add even simple features, given the amount of existing code that it will affect. :-)

I think the feature should work reliably now, but I may of course have missed some cases as well. Could you please also have a final look and do some testing with your use-cases, to see whether the change is fine in its current state?

Personally, I'd like to continue this change to cover also tiles from a tileset image (see also #2863). If we store the sub-rectangle on each tile, we can entirely avoid the need to even cut out each tile's image from the tileset image (apart from where it is used as an icon). But I guess it's better to continue that on another pull request.

2022-05-17 12:55 UTC, devnewton commented
I have made some tests and it works well. UX/UI could be better, but this will be for other pull requests :-)

Here is the test map I used, feel free to add it as Tiled sample. It show background object layers, a tile layer, and an animated object with various tile sizes.

[forest.zip](https://github.com/mapeditor/tiled/files/8708403/forest.zip)
)

2022-05-17 13:39 UTC, bjorn commented
> Here is the test map I used, feel free to add it as Tiled sample. It show background object layers, a tile layer, and an animated object with various tile sizes.

Thanks! I've just committed this example then.

2022-05-17 13:47 UTC, merged