Smartly choose a new layer name to prevent duplicate names
mapeditor/tiled pull request #3501
Opened 2022-10-14 02:22 UTC by lhiginbotham

Fixes #3452 by attempting to use the default "<Type> Layer <Number>" name, incrementing <Number> if any collisions occur.

2022-10-17 20:00 UTC, bjorn requested changes
Patch looks good, but I added some comments that need to be addressed. :-)

2022-10-21 00:23 UTC, lhiginbotham commented on src/tiled/mapdocument.cpp
> +    fillLayerNames(mMap->allLayers(layerType));
Done, thanks!

2022-10-21 00:23 UTC, lhiginbotham commented on src/tiled/mapdocument.cpp
> +QString MapDocument::getNewLayerName(Layer::TypeFlag layerType) const
Got it, thanks!

2022-10-21 00:24 UTC, lhiginbotham commented on src/tiled/mapdocument.cpp
> +    const char* parametricName = nullptr;
Fixed 👍

2022-10-21 00:24 UTC, lhiginbotham commented on src/tiled/mapdocument.cpp
> +        candidateName = tr(parametricName).arg(++number);
Thanks for pointing this out to me, I don't work with Qt all that much

2022-10-21 00:25 UTC, lhiginbotham commented
> Patch looks good, but I added some comments that need to be addressed. :-)

@bjorn - changes have been made, please check it out 😃

2022-10-21 07:46 UTC, merged

2022-10-21 07:53 UTC, bjorn commented
@lhiginbotham Thanks! :-)